/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',   // picks up sidebar_position frontmatter from docs/
    },
  ],
};

export default sidebars;
